/*
  # Seed blog_posts rows for Calvia Health

  This migration inserts baseline blog post rows so "expand_*" migrations can safely UPDATE by slug.

  Notes:
  - Idempotent: ON CONFLICT (slug) DO NOTHING
  - Content is intentionally lightweight; expand migrations provide long-form HTML.
*/

INSERT INTO blog_posts (
  slug,
  title,
  meta_description,
  focus_keyword,
  excerpt,
  content,
  featured_image_url,
  featured_image_alt,
  category,
  tags,
  read_time_minutes,
  published,
  published_at,
  created_at
)
VALUES
  (
    'best-dentist-mallorca',
    'Best Dentist in Mallorca for Expats',
    'How to compare dental clinics in Mallorca, estimate treatment costs, and find English-speaking dentists in Calvia.',
    'best dentist in Mallorca for expats',
    'Compare clinics, qualifications, and treatment pricing for dental care in Mallorca with practical guidance for expats.',
    '<h2>Best Dentist in Mallorca for Expats</h2><p>Compare clinics, qualifications, and treatment pricing for dental care in Mallorca with practical guidance for expats.</p>',
    'https://images.pexels.com/photos/1170979/pexels-photo-1170979.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'Best Dentist in Mallorca for Expats',
    'medical',
    ARRAY['medical', 'calvia', 'mallorca']::text[],
    18,
    true,
    '2026-02-13T00:00:00Z'::timestamptz,
    '2026-02-13T00:00:00Z'::timestamptz
  ),
  (
    'pharmacies-calvia',
    'Pharmacies in Calvia: Where to Go and How It Works',
    'How pharmacies work in Calvia, Mallorca: prescriptions, over-the-counter medicines, farmacias de guardia, and where to go in Santa Ponsa, Palmanova, Portals Nous, and Peguera.',
    'pharmacies in calvia mallorca',
    'A practical guide to prescriptions, after-hours pharmacies, and where to get help fast in Calvia, Mallorca.',
    '<h2>Pharmacies in Calvia</h2><p>A practical guide to prescriptions, after-hours pharmacies, and where to get help fast in Calvia, Mallorca.</p>',
    'https://images.pexels.com/photos/3683108/pexels-photo-3683108.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'Pharmacies in Calvia: Where to Go and How It Works',
    'medical',
    ARRAY['medical', 'calvia', 'mallorca']::text[],
    10,
    true,
    '2026-02-13T12:00:00Z'::timestamptz,
    '2026-02-13T12:00:00Z'::timestamptz
  ),
  (
    'snoring-treatment-mallorca',
    'Snoring Treatment in Mallorca',
    'A practical guide to snoring and sleep apnea treatment options in Mallorca, including ENT and sleep clinics.',
    'snoring treatment mallorca',
    'Understand common snoring causes, specialist pathways, and what to expect from assessments in Mallorca.',
    '<h2>Snoring Treatment in Mallorca</h2><p>Understand common snoring causes, specialist pathways, and what to expect from assessments in Mallorca.</p>',
    'https://images.pexels.com/photos/3938022/pexels-photo-3938022.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'Snoring Treatment in Mallorca',
    'medical',
    ARRAY['medical', 'calvia', 'mallorca']::text[],
    14,
    true,
    '2026-02-13T00:00:00Z'::timestamptz,
    '2026-02-13T00:00:00Z'::timestamptz
  ),
  (
    'eye-surgery-mallorca',
    'Eye Surgery in Mallorca: Lasik and Beyond',
    'What to know before Lasik, cataract surgery, or vision correction treatment in Mallorca.',
    'eye surgery mallorca',
    'Compare eye care providers, treatment options, and recovery expectations for common vision procedures.',
    '<h2>Eye Surgery in Mallorca</h2><p>Compare eye care providers, treatment options, and recovery expectations for common vision procedures.</p>',
    'https://images.pexels.com/photos/8460157/pexels-photo-8460157.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'Eye Surgery in Mallorca: Lasik and Beyond',
    'medical',
    ARRAY['medical', 'calvia', 'mallorca']::text[],
    15,
    true,
    '2026-02-13T00:00:00Z'::timestamptz,
    '2026-02-13T00:00:00Z'::timestamptz
  ),
  (
    'pediatrician-mallorca',
    'Finding a Pediatrician in Mallorca',
    'How families in Calvia can find trusted pediatric care, urgent support, and multilingual clinics.',
    'pediatrician mallorca',
    'A family-focused guide to pediatric services, appointment planning, and urgent care options in Mallorca.',
    '<h2>Finding a Pediatrician in Mallorca</h2><p>A family-focused guide to pediatric services, appointment planning, and urgent care options in Mallorca.</p>',
    'https://images.pexels.com/photos/7089401/pexels-photo-7089401.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'Finding a Pediatrician in Mallorca',
    'medical',
    ARRAY['medical', 'calvia', 'mallorca']::text[],
    12,
    true,
    '2026-02-13T00:00:00Z'::timestamptz,
    '2026-02-13T00:00:00Z'::timestamptz
  ),
  (
    'emergency-medical-services-calvia',
    'Emergency Medical Services in Calvia',
    'Emergency numbers, response expectations, and hospital options for urgent care in Calvia and Palma.',
    'emergency medical services calvia',
    'Know who to call, where to go, and what details to provide in a medical emergency in Calvia.',
    '<h2>Emergency Medical Services in Calvia</h2><p>Know who to call, where to go, and what details to provide in a medical emergency in Calvia.</p>',
    'https://images.pexels.com/photos/7579831/pexels-photo-7579831.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'Emergency Medical Services in Calvia',
    'medical',
    ARRAY['medical', 'calvia', 'mallorca']::text[],
    11,
    true,
    '2026-02-13T00:00:00Z'::timestamptz,
    '2026-02-13T00:00:00Z'::timestamptz
  ),
  (
    'best-massage-therapists-calvia',
    'Best Massage Therapists in Calvia',
    'How to choose massage therapists in Calvia by treatment goals, specialization, and clinic quality.',
    'best massage therapists calvia',
    'Find sports, therapeutic, and relaxation massage options with tips on provider quality and session planning.',
    '<h2>Best Massage Therapists in Calvia</h2><p>Find sports, therapeutic, and relaxation massage options with tips on provider quality and session planning.</p>',
    'https://images.pexels.com/photos/3768916/pexels-photo-3768916.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'Best Massage Therapists in Calvia',
    'wellness',
    ARRAY['wellness', 'calvia', 'mallorca']::text[],
    10,
    true,
    '2026-02-13T00:00:00Z'::timestamptz,
    '2026-02-13T00:00:00Z'::timestamptz
  ),
  (
    'personal-trainers-calvia-mallorca',
    'Personal Trainers in Calvia, Mallorca',
    'How to evaluate personal trainers in Calvia for weight loss, performance, and rehabilitation goals.',
    'personal trainers calvia mallorca',
    'Compare coaching styles, certifications, and pricing structures for personal training in Calvia.',
    '<h2>Personal Trainers in Calvia</h2><p>Compare coaching styles, certifications, and pricing structures for personal training in Calvia.</p>',
    'https://images.pexels.com/photos/3825527/pexels-photo-3825527.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'Personal Trainers in Calvia, Mallorca',
    'wellness',
    ARRAY['wellness', 'calvia', 'mallorca']::text[],
    10,
    true,
    '2026-02-13T00:00:00Z'::timestamptz,
    '2026-02-13T00:00:00Z'::timestamptz
  ),
  (
    'gyms-fitness-calvia',
    'Gyms and Fitness Centres in Calvia',
    'Find gyms and fitness centres in Calvia, Mallorca: Santa Ponsa, Palmanova, Magaluf, and Portals Nous. Day passes, classes, pricing, and how to choose.',
    'gyms in calvia mallorca',
    'A local guide to gyms, CrossFit boxes, boutique studios, and municipal sports centres in Calvia, Mallorca.',
    '<h2>Gyms and Fitness Centres in Calvia</h2><p>A local guide to gyms, CrossFit boxes, boutique studios, and municipal sports centres in Calvia, Mallorca.</p>',
    'https://images.pexels.com/photos/1552242/pexels-photo-1552242.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'Gyms and Fitness Centres in Calvia',
    'wellness',
    ARRAY['wellness', 'calvia', 'mallorca']::text[],
    11,
    true,
    '2026-02-13T12:05:00Z'::timestamptz,
    '2026-02-13T12:05:00Z'::timestamptz
  ),
  (
    'luxury-wellness-retreats-mallorca',
    'Luxury Wellness Retreats in Mallorca',
    'A guide to premium wellness retreat options near Calvia, including spa, yoga, and recovery programs.',
    'luxury wellness retreats mallorca',
    'Explore retreat formats, cost ranges, and planning tips for restorative wellness stays in Mallorca.',
    '<h2>Luxury Wellness Retreats in Mallorca</h2><p>Explore retreat formats, cost ranges, and planning tips for restorative wellness stays in Mallorca.</p>',
    'https://images.pexels.com/photos/3225531/pexels-photo-3225531.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'Luxury Wellness Retreats in Mallorca',
    'spa-hotels',
    ARRAY['spa-hotels', 'calvia', 'mallorca']::text[],
    12,
    true,
    '2026-02-13T00:00:00Z'::timestamptz,
    '2026-02-13T00:00:00Z'::timestamptz
  ),
  (
    'diet-nutritionist-mallorca',
    'Diet and Nutritionist Services in Mallorca',
    'How to find qualified nutrition support in Mallorca for weight goals, metabolic health, and lifestyle changes.',
    'diet nutritionist mallorca',
    'Practical steps for choosing a nutrition professional and building a realistic plan for long-term outcomes.',
    '<h2>Diet and Nutritionist Services in Mallorca</h2><p>Practical steps for choosing a nutrition professional and building a realistic plan for long-term outcomes.</p>',
    'https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'Diet and Nutritionist Services in Mallorca',
    'lifestyle',
    ARRAY['lifestyle', 'calvia', 'mallorca']::text[],
    9,
    true,
    '2026-02-13T00:00:00Z'::timestamptz,
    '2026-02-13T00:00:00Z'::timestamptz
  ),
  (
    'natural-health-shops-mallorca',
    'Natural Health Shops in Mallorca',
    'Where to find supplements and natural health products in Mallorca, and how to verify quality.',
    'natural health shops mallorca',
    'A shopper-friendly guide to natural product stores, label reading, and safe supplement selection.',
    '<h2>Natural Health Shops in Mallorca</h2><p>A shopper-friendly guide to natural product stores, label reading, and safe supplement selection.</p>',
    'https://images.pexels.com/photos/5998475/pexels-photo-5998475.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'Natural Health Shops in Mallorca',
    'lifestyle',
    ARRAY['lifestyle', 'calvia', 'mallorca']::text[],
    8,
    true,
    '2026-02-13T00:00:00Z'::timestamptz,
    '2026-02-13T00:00:00Z'::timestamptz
  ),
  (
    'healthy-restaurants-calvia',
    'Healthy Restaurants in Calvia',
    'A guide to healthy dining in Calvia, including nutrition-conscious menus and family-friendly options.',
    'healthy restaurants calvia',
    'Discover healthy dining options and menu strategies for balanced eating across Calvia.',
    '<h2>Healthy Restaurants in Calvia</h2><p>Discover healthy dining options and menu strategies for balanced eating across Calvia.</p>',
    'https://images.pexels.com/photos/263402/pexels-photo-263402.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'Healthy Restaurants in Calvia',
    'lifestyle',
    ARRAY['lifestyle', 'calvia', 'mallorca']::text[],
    8,
    true,
    '2026-02-13T00:00:00Z'::timestamptz,
    '2026-02-13T00:00:00Z'::timestamptz
  ),
  (
    'health-insurance-mallorca',
    'Health Insurance in Mallorca',
    'How health insurance works in Mallorca, including private plan options and expat decision criteria.',
    'health insurance mallorca',
    'Understand policy types, network access, and common tradeoffs when choosing health insurance in Spain.',
    '<h2>Health Insurance in Mallorca</h2><p>Understand policy types, network access, and common tradeoffs when choosing health insurance in Spain.</p>',
    'https://images.pexels.com/photos/7176026/pexels-photo-7176026.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'Health Insurance in Mallorca',
    'insurance',
    ARRAY['insurance', 'calvia', 'mallorca']::text[],
    13,
    true,
    '2026-02-13T00:00:00Z'::timestamptz,
    '2026-02-13T00:00:00Z'::timestamptz
  ),
  (
    'private-vs-public-health-insurance-spain',
    'Private vs Public Health Insurance in Spain',
    'A side-by-side comparison of private and public healthcare access in Spain for residents and expats.',
    'private vs public health insurance spain',
    'Compare waiting times, specialist access, language support, and cost structures across systems.',
    '<h2>Private vs Public Health Insurance in Spain</h2><p>Compare waiting times, specialist access, language support, and cost structures across systems.</p>',
    'https://images.pexels.com/photos/4506105/pexels-photo-4506105.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'Private vs Public Health Insurance in Spain',
    'insurance',
    ARRAY['insurance', 'calvia', 'mallorca']::text[],
    11,
    true,
    '2026-02-13T00:00:00Z'::timestamptz,
    '2026-02-13T00:00:00Z'::timestamptz
  ),
  (
    'health-insurance-over-65-mallorca',
    'Health Insurance Over 65 in Mallorca',
    'Coverage options, eligibility realities, and pricing expectations for over-65 insurance in Mallorca.',
    'health insurance over 65 mallorca',
    'A practical planning guide for older residents reviewing private insurance options in Mallorca.',
    '<h2>Health Insurance Over 65 in Mallorca</h2><p>A practical planning guide for older residents reviewing private insurance options in Mallorca.</p>',
    'https://images.pexels.com/photos/8376292/pexels-photo-8376292.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'Health Insurance Over 65 in Mallorca',
    'insurance',
    ARRAY['insurance', 'calvia', 'mallorca']::text[],
    10,
    true,
    '2026-02-13T00:00:00Z'::timestamptz,
    '2026-02-13T00:00:00Z'::timestamptz
  ),
  (
    'top-spas-calvia',
    'Top Spas in Calvia',
    'How to choose a high-quality spa in Calvia for recovery, stress reduction, and wellness routines.',
    'top spas calvia',
    'Compare spa formats, treatment menus, and what to prioritize when booking wellness sessions.',
    '<h2>Top Spas in Calvia</h2><p>Compare spa formats, treatment menus, and what to prioritize when booking wellness sessions.</p>',
    'https://images.pexels.com/photos/3845766/pexels-photo-3845766.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'Top Spas in Calvia',
    'spa-hotels',
    ARRAY['spa-hotels', 'calvia', 'mallorca']::text[],
    9,
    true,
    '2026-02-13T00:00:00Z'::timestamptz,
    '2026-02-13T00:00:00Z'::timestamptz
  ),
  (
    'thalassotherapy-mallorca',
    'Thalassotherapy in Mallorca',
    'An introduction to thalassotherapy benefits, treatment types, and where to find it in Mallorca.',
    'thalassotherapy mallorca',
    'Learn what thalassotherapy includes, who it suits best, and how to choose reputable centers.',
    '<h2>Thalassotherapy in Mallorca</h2><p>Learn what thalassotherapy includes, who it suits best, and how to choose reputable centers.</p>',
    'https://images.pexels.com/photos/6528908/pexels-photo-6528908.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'Thalassotherapy in Mallorca',
    'spa-hotels',
    ARRAY['spa-hotels', 'calvia', 'mallorca']::text[],
    9,
    true,
    '2026-02-13T00:00:00Z'::timestamptz,
    '2026-02-13T00:00:00Z'::timestamptz
  ),
  (
    'top-boutique-hotels-mallorca',
    'Top Boutique Hotels in Mallorca for Wellness',
    'A guide to boutique hotels in Mallorca with strong wellness offerings and health-focused experiences.',
    'top boutique hotels mallorca',
    'Compare wellness-friendly boutique stays and plan a healthier, more restorative visit to Mallorca.',
    '<h2>Top Boutique Hotels in Mallorca for Wellness</h2><p>Compare wellness-friendly boutique stays and plan a healthier, more restorative visit to Mallorca.</p>',
    'https://images.pexels.com/photos/8436730/pexels-photo-8436730.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'Top Boutique Hotels in Mallorca for Wellness',
    'spa-hotels',
    ARRAY['spa-hotels', 'calvia', 'mallorca']::text[],
    10,
    true,
    '2026-02-13T00:00:00Z'::timestamptz,
    '2026-02-13T00:00:00Z'::timestamptz
  )
ON CONFLICT (slug) DO NOTHING;

